---
title: "Nov16DataVisualizationinR"
author: "Amelia Guo"
date: '2018-11-16'
output: md_document
---
#Notes for Data Visualization with ggplot2 (Part1) (DataCamp)

##1. Introduction
- Exploratory plots aren't meant to be pretty. 
- Have to specify when a variable is categorical 

```{R}
# Load the ggplot2 package
library(ggplot2)

# Change the command below so that cyl is treated as factor
ggplot(mtcars, aes(x = factor(cyl), y = mpg)) +
  geom_point()

#X axis doesnot contain values outside of the dataset

```

```{R}
# Can change the COLOUR of the points based on the data in a certain column: ex. the displacement of the car engine
ggplot(mtcars, aes(x = wt, y = mpg, color = disp)) +
  geom_point()
```


```{R}
# Can change the SIZE of the points based on the data in a certain column: ex. the displacement of the car engine
ggplot(mtcars, aes(x = wt, y = mpg, size = disp)) +
  geom_point()
```

Can't change the shape of the points based on displacement of the car engine because 'A continuous variable can not be mapped to shape', means that shape doesn't exist on a continuous scale here.


```{R}
#Can fit a smoothened line over the data points with geom_smooth()
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point() +
  geom_smooth()
#can call se = FALSE within the geom_smooth function to get rid of error shading
```

```{R}
#Can plot just the smoothen curve and colour based on column of clarity
ggplot(diamonds, aes(x = carat, y = price, color = clarity)) +
  geom_smooth()
```

```{R}
#Can plot the points and colour based on clarity + change opacity
ggplot(diamonds, aes(x = carat, y = price, color = clarity)) + geom_point(alpha = 0.4)
```


```{R}
# Create the object containing the data and aes layers: dia_plot
dia_plot <- ggplot(diamonds, aes(x = carat, y = price))

# Add a geom layer with + and geom_point()
dia_plot + geom_point()

# Add the same geom layer, but with aes() inside
dia_plot + geom_point(aes(color = clarity))
```


##2. Data
```{R}
# Plot the correct variables of mtcars
plot(mtcars$wt, mtcars$mpg, col = mtcars$cyl)

# Change cyl inside mtcars to a factor
mtcars$fcyl <- as.factor(mtcars$cyl)

# Make the same plot as in the first instruction
plot(mtcars$wt, mtcars$mpg, col = mtcars$fcyl)
```

```{R}
# lm for each cyl value and lm for whole group (with group = 1)
ggplot(mtcars, aes(x = wt, y = mpg, col = cyl)) +
 geom_point() +
  geom_smooth(se = FALSE, method = lm) +
  geom_smooth(aes(group = 1), method = lm, se = FALSE, linetype = 2)
```



```{R}
library(tidyr)
# Consider the structure of iris, iris.wide and iris.tidy (in that order)
str(iris)

# Tidy up the data 
iris.tidy <- iris %>%
  gather(key, Value, -Species) %>%
  separate(key, c("Part", "Measure"), "\\.")
  
str(iris.tidy)

# Plot the tidy data
ggplot(iris.tidy, aes(x = Species, y = Value, col = Part)) +
  geom_jitter() +
  facet_grid(. ~ Measure)
```

##3. Aesthetics
```{R}
#can colour outline and fill in the points with diff colours
ggplot(mtcars, aes(x = wt, y = mpg, fill = cyl, col = am)) +
  geom_point(shape = 21, size = 4, alpha = 0.6)
```

```{R}
my_color <- "#4ABEFF"
#colour inside geom_point will override what's said above
ggplot(mtcars, aes(x = wt, y = mpg, fill = cyl)) +
  geom_point(colour = my_color, size = 10, shape = 23)
```

In this chapter we saw aesthetics and attributes. Variables in a data frame are mapped to aesthetics in aes(). (e.g. aes(col = cyl)) within ggplot(). Visual elements are set by attributes in specific geom layers (geom_point(col = "red")). Don't confuse these two things.

```{R}
#can show 5 dimensions here just within aesthetics
ggplot(mtcars, aes(x = mpg, y = qsec, colour = factor(cyl), shape = factor(am), size = (hp/wt))) + geom_point()
```

Label and shape are only applicable to categorical data.

```{R}
#base layer
cyl.am <- ggplot(mtcars, aes(x = factor(cyl), fill = factor(am)))

cyl.am + geom_bar() #position is stack by default

# can change the position, scales, and legend
val = c("#E41A1C", "#377EB8")
lab = c("Manual", "Automatic")
cyl.am +
  geom_bar(position = "dodge") +
  scale_x_discrete('Cylinders') + 
  scale_y_continuous('Number') +
  scale_fill_manual('Transmission', 
                    values = val,
                    labels = lab) 

```


```{R}
#if no y variable, put 0. also, geom_jitter so that points are not in a straight line, set limits on axis
ggplot(mtcars, aes(x = mpg, y = 0)) +
  geom_jitter() +
  scale_y_continuous(limits = c(-2, 2))
```

You'll have to deal with overplotting when you have:
- Large datasets
- Imprecise data and so points are not clearly separated on your plot (you saw this in the video with the iris dataset)
- Interval data (i.e. data appears at fixed values)
- Aligned data values on a single axis

Solutions:
```{R}
#size 1 is hollow points, lower transparency
ggplot(mtcars, aes(x = wt, y = mpg, colour = cyl)) +
  geom_point(size = 4, shape = 1, alpha = 0.6)

# Scatter plot: carat (x), price (y), clarity (color)
ggplot(diamonds, aes(x = carat, y = price, colour = clarity)) +
  geom_point()
# Adjust for overplotting
ggplot(diamonds, aes(x = carat, y = price, colour = clarity)) +
  geom_point(alpha = 0.5)


# Scatter plot: clarity (x), carat (y), price (color)
ggplot(diamonds, aes(x = clarity, y = carat, colour = price)) +
  geom_point(alpha = 0.5)
# Dot plot with jittering
ggplot(diamonds, aes(x = clarity, y = carat, colour = price)) +
  geom_point(alpha = 0.5, position = "jitter")

```

##4. Geometries
```{R}
#jittering
ggplot(mtcars, aes(x = cyl, y = wt)) +
  geom_point(position = position_jitter(0.1))

```


```{R}
#for histograms, ..xxx.. stores how many counts are in each bin 
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram(binwidth = 1, aes(y = ..density..), fill = '#377EB8')

```



```{R}
#different bar graphs

# Change the position argument to stack (this is the default)
ggplot(mtcars, aes(x = cyl, fill = am)) +
  geom_bar(position = "stack")

# Change the position argument to fill
ggplot(mtcars, aes(x = cyl, fill = am)) +
  geom_bar(position = "fill")

# Change the position argument to dodge
ggplot(mtcars, aes(x = cyl, fill = am)) +
  geom_bar(position = "dodge")

```

stack (the default), dodge (preferred), and fill (to show proportions)

```{R}
#show overlapping dodge bar graphs
posn_d <- position_dodge(width = 0.2)
ggplot(mtcars, aes(x = cyl, fill = am)) +
  geom_bar(position = posn_d, alpha = 0.6)

```


```{R}
ggplot(mtcars, aes(mpg, colour = cyl)) +
  geom_freqpoly(binwidth = 1, position = "identity")
```

```{R}
# Example of how to use a brewed color palette
ggplot(mtcars, aes(x = cyl, fill = am)) +
  geom_bar() +
  scale_fill_brewer(palette = "Set1")

```


```{R}
#OVERLAPPING 
ggplot(mtcars, aes(mpg, fill = am)) +
  geom_histogram(binwidth = 1, position = "identity", alpha = 0.4)
```


  
```{R}
#Making line plots with geom_line()
ggplot(economics, aes(x = date, y = unemploy/pop)) + geom_line()

```
